
"""
Secondary Test Suite: Feedback, Reports, and Materials
Uses EXISTING users (fetched from DB) to generate:
- 2 New Materials
- 2 Feedbacks
- 2 Seller Reports

Run with: python test_feedback_materials.py
"""

import asyncio
import requests
import random
from sqlalchemy import text
from db.connection import AsyncSessionLocal

BASE_URL = "http://localhost:8000/api"
PASSWORD = "password123"  # Standard password from seeding script

async def get_existing_users():
    """Fetch one random seller and one buyer from DB"""
    async with AsyncSessionLocal() as session:
        # Get a Seeded Seller (from test_api.py, emails start with 'seller')
        res = await session.execute(text("SELECT email FROM organization WHERE email LIKE 'seller%' LIMIT 1"))
        seller_email = res.scalar()
        
        # Get a Seeded Buyer
        res = await session.execute(text("SELECT email FROM buyer WHERE email LIKE 'buyer%' LIMIT 1"))
        buyer_email = res.scalar()
        
        return seller_email, buyer_email

def login(username, role_type):
    url = f"{BASE_URL}/auth/login"
    resp = requests.post(url, data={"username": username, "password": PASSWORD})
    if resp.status_code == 200:
        return resp.json().get("access_token")
    print(f"Login failed for {username}: {resp.text}")
    return None

def test_create_materials(seller_token):
    print("\n--- Creating 2 New Materials ---")
    headers = {"Authorization": f"Bearer {seller_token}"}
    created_ids = []
    
    for i in range(2):
        payload = {
            "title": f"Secondary Test Material {i+1}",
            "category": "Metal",
            "description": "Created via secondary test script",
            "quantity_value": 100 * (i+1),
            "quantity_unit": "kg",
            "condition": "Used",
            "photos": []
        }
        resp = requests.post(f"{BASE_URL}/materials/", json=payload, headers=headers)
        if resp.status_code == 200:
            mid = resp.json().get('material_id')
            print(f"✅ Material Created: ID {mid}")
            created_ids.append(mid)
        else:
            print(f"❌ Creation Failed: {resp.text}")
            
    return created_ids

def test_feedback_and_reports(seller_token, buyer_token, material_id):
    print(f"\n--- generating Feedback & Reports (Mat {material_id}) ---")
    
    headers_buyer = {"Authorization": f"Bearer {buyer_token}"}
    headers_seller = {"Authorization": f"Bearer {seller_token}"}
    
    target_mat_id = material_id
    
    # Buyer Requests
    req_payload = {"requested_quantity": 1, "message": "For testing feedback"}
    r_resp = requests.post(f"{BASE_URL}/materials/{target_mat_id}/request", json=req_payload, headers=headers_buyer)
    
    if r_resp.status_code == 200:
        req_id = r_resp.json()['request_id']
        print(f"  Created Request {req_id} for setup")
        
        # Seller Accepts & Completes
        # 1. Accept
        s1 = requests.put(f"{BASE_URL}/requests/{req_id}/status", json={"status": "accepted"}, headers=headers_seller)
        if s1.status_code != 200:
             print(f"  Failed to accept: {s1.text}")
             return

        # 2. Complete
        s2 = requests.put(f"{BASE_URL}/requests/{req_id}/status", json={"status": "completed"}, headers=headers_seller)
        if s2.status_code != 200:
             print(f"  Failed to complete: {s2.text}")
             return
        
        # 1. SUBMIT FEEDBACK (Buyer)
        fb_payload = {"rating": 5, "comment": "Test Feedback for script"}
        fb_resp = requests.post(f"{BASE_URL}/interactions/{req_id}/feedback", json=fb_payload, headers=headers_buyer)
        if fb_resp.status_code == 200:
            print(f"✅ Feedback Added for Request {req_id}")
        else:
            print(f"❌ Feedback Failed: {fb_resp.text}")
            
        # 2. SUBMIT REPORT (Seller)
        rp_payload = {"reason": "Test Report", "description": "Generated by script"}
        rp_resp = requests.post(f"{BASE_URL}/interactions/requests/{req_id}/report", json=rp_payload, headers=headers_seller)
        if rp_resp.status_code == 200:
            print(f"✅ Report Filed for Request {req_id}")
        else:
            print(f"❌ Report Failed: {rp_resp.text}")

async def main():
    print("Fetching existing users from DB...")
    try:
        seller_email, buyer_email = await get_existing_users()
    except Exception as e:
        print(f"Error accessing DB: {e}")
        return

    if not seller_email or not buyer_email:
        print("Could not find a Seller and Buyer in DB. Run test_api.py first.")
        return
        
    print(f"Found Seller: {seller_email}")
    print(f"Found Buyer: {buyer_email}")
    
    seller_token = login(seller_email, "organization")
    buyer_token = login(buyer_email, "buyer")
    
    if seller_token and buyer_token:
        # Create materials first
        created_mats = test_create_materials(seller_token)
        
        if len(created_mats) >= 2:
            # Use the created materials for the feedback loop
            test_feedback_and_reports(seller_token, buyer_token, created_mats[0])
            test_feedback_and_reports(seller_token, buyer_token, created_mats[1])
        else:
            print("Not enough materials created to test feedback loops")

if __name__ == "__main__":
    if hasattr(asyncio, 'WindowsSelectorEventLoopPolicy'):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(main())
